/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  servicesSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',
    },
  ],
};

module.exports = sidebars;
