#!/usr/bin/env node
/**
 * Sidebar Update Script
 * Automatically updates service-specific sidebar.js files after a sync.
 * If the sidebar uses Docusaurus autogenerated structure, this is a no-op.
 */

const fs = require('fs');
const path = require('path');

const summary = JSON.parse(fs.readFileSync('sync-summary.json', 'utf-8'));
const repoName = summary.repository_name;

console.log(`📝 Updating sidebar for: ${repoName}`);

const sidebarPath = path.join('docs', 'services', repoName, 'sidebar.js');

if (!fs.existsSync(sidebarPath)) {
  console.log(`⚠️  Sidebar not found at ${sidebarPath}`);
  console.log(`   This is expected for new services — Docusaurus will autogenerate the sidebar.`);
  process.exit(0);
}

let sidebarContent = fs.readFileSync(sidebarPath, 'utf-8');

if (sidebarContent.includes("type: 'autogenerated'")) {
  console.log(`✨ Sidebar uses autogenerated structure — no manual updates needed.`);
  process.exit(0);
}

console.log(`🔧 Manual sidebar structure detected — updating entries...`);

// Remove deleted files
summary.deleted_files.forEach(file => {
  const docId = file.target
    .replace(/^docs\/services\//, '')
    .replace(/\.(md|mdx)$/, '');
  const entryRegex = new RegExp(`\\s*['"\`]${docId}['"\`],?\\s*`, 'g');
  const before = sidebarContent.length;
  sidebarContent = sidebarContent.replace(entryRegex, '');
  if (sidebarContent.length < before) {
    console.log(`   🗑️  Removed: ${docId}`);
  }
});

// Add new files
summary.synced_files.forEach(file => {
  const docId = file.target
    .replace(/^docs\/services\//, '')
    .replace(/\.(md|mdx)$/, '');

  if (sidebarContent.includes(docId)) {
    console.log(`   ⏭️  Already exists: ${docId}`);
    return;
  }

  const entry = `      '${docId}',`;
  const itemsArrayRegex = /(items:\s*\[)/;
  if (itemsArrayRegex.test(sidebarContent)) {
    sidebarContent = sidebarContent.replace(itemsArrayRegex, `$1\n${entry}`);
    console.log(`   ✅ Added: ${docId}`);
  } else {
    const sidebarArrayRegex = /(sidebar:\s*\[)/;
    if (sidebarArrayRegex.test(sidebarContent)) {
      sidebarContent = sidebarContent.replace(sidebarArrayRegex, `$1\n${entry}`);
      console.log(`   ✅ Added: ${docId}`);
    } else {
      console.warn(`   ⚠️  Could not find insertion point for: ${docId}`);
    }
  }
});

fs.writeFileSync(sidebarPath, sidebarContent);
console.log(`\n💾 Sidebar updated successfully`);
